### ISSUE TITLE
Error within 

### ISSUE THREAD

**Issue by algotechnology** [symphonyoss/symphony-java-client#118]
When you connect to a roomthat has a rbot and other in it (ie not direct chat) we are seeing this error below.  Seems to occur all the time.  Not a problem for direct messages.  Anyone else seen this or got a solution please?

Thanks

Exception in thread "DataFeedWorker: xxxx" java.lang.NoSuchMethodError: org.symphonyoss.symphony.pod.api.StreamsApi.v3RoomIdInfoGet(Ljava/lang/String;Ljava/lang/String;)Lorg/symphonyoss/symphony/pod/model/V3RoomDetail;
	at org.symphonyoss.symphony.clients.impl.StreamsClientImpl.getRoomDetail(StreamsClientImpl.java:296)
	at org.symphonyoss.client.services.RoomService.joinRoom(RoomService.java:166)
	at org.symphonyoss.client.services.RoomService.addRoom(RoomService.java:334)
	at org.symphonyoss.client.services.RoomService.onMessage(RoomService.java:197)
	at org.symphonyoss.client.services.MessageService.onEvent(MessageService.java:285)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.symphonyoss.client.services.DataFeedWorker.readDatafeed(DataFeedWorker.java:146)
	at org.symphonyoss.client.services.DataFeedWorker.run(DataFeedWorker.java:79)
	at java.lang.Thread.run(Thread.java:745)

**Comment by ftbb** [comment]
What version of the SJC are you using?

**Comment by algotechnology** [comment]
1.1.5-SNAPSHOT and also tried 1.1.4 as well
<groupId>org.symphonyoss.symphony</groupId>
<artifactId>symphony-client</artifactId>

**Comment by algotechnology** [comment]
[INFO] +- org.symphonyoss.symphony:symphony-client:jar:1.1.5-SNAPSHOT:compile
[INFO] +- org.symphonyoss.symphony:symphony-java-client:pom:1.0.3:compile
[INFO] +- org.symphonyoss.symphony:symphony-authenticator-java-jersey2-client:jar:1.47.0:compile
[INFO] +- org.symphonyoss.symphony:symphony-agent:pom:1.0.1:compile
[INFO] +- org.symphonyoss.symphony:symphony-authenticator-api:jar:1.0.2-SNAPSHOT:compile
[INFO] +- org.symphonyoss.symphony:symphony-agent-java-jersey2-client:jar:1.47.0:compile
[INFO] +- org.symphonyoss.symphony:symphony-pod:pom:1.0.2-SNAPSHOT:compile
[INFO] +- org.symphonyoss.symphony:symphony-pod-java-jersey2-client:jar:1.47.0:compile

**Comment by ftbb** [comment]
That is why you are having issues. All you should have in your pom is:

   <dependency>
  <groupId>org.symphonyoss.symphony</groupId>
     <artifactId>symphony-client</artifactId>
      <version>1.1.5-SNAPSHOT</version>
    </dependency>
   <dependency>


You might have inherited underlying jars from other dependencies or classpath.  Run: mvn dependency:tree without grep to understand where you are getting older jars from.

It needs to look like what I have posted prior.

**Comment by algotechnology** [comment]
Thanks.  I will test that tomorrow.  Appreciate the help

**Comment by algotechnology** [comment]
Thanks - That worked perfectly.  Appreciate your help.

**Comment by ftbb** [comment]
Cool..happy to help.
