### ISSUE TITLE
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "roles" 

### ISSUE THREAD

**Issue by darkmanAmazigh** [symphonyoss/symphony-java-client#124]
Hi,

since little days, without changing anything (i think !!), i got this error message, and my client is not working

		java.lang.IllegalStateException: Failed to load ApplicationContext
			at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:124)
			at org.springframework.test.context.support.DefaultTestContext.getApplicationContext(DefaultTestContext.java:83)
			at org.springframework.test.context.web.ServletTestExecutionListener.setUpRequestContextIfNecessary(ServletTestExecutionListener.java:189)
			at org.springframework.test.context.web.ServletTestExecutionListener.prepareTestInstance(ServletTestExecutionListener.java:131)
			at org.springframework.test.context.TestContextManager.prepareTestInstance(TestContextManager.java:230)
			at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.createTest(SpringJUnit4ClassRunner.java:228)
			at org.springframework.test.context.junit4.SpringJUnit4ClassRunner$1.runReflectiveCall(SpringJUnit4ClassRunner.java:287)
			at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
			at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.methodBlock(SpringJUnit4ClassRunner.java:289)
			at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:247)
			at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.runChild(SpringJUnit4ClassRunner.java:94)
			at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
			at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
			at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
			at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
			at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
			at org.springframework.test.context.junit4.statements.RunBeforeTestClassCallbacks.evaluate(RunBeforeTestClassCallbacks.java:61)
			at org.springframework.test.context.junit4.statements.RunAfterTestClassCallbacks.evaluate(RunAfterTestClassCallbacks.java:70)
			at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
			at org.springframework.test.context.junit4.SpringJUnit4ClassRunner.run(SpringJUnit4ClassRunner.java:191)
			at org.eclipse.jdt.internal.junit4.runner.JUnit4TestReference.run(JUnit4TestReference.java:89)
			at org.eclipse.jdt.internal.junit.runner.TestExecution.run(TestExecution.java:41)
			at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:541)
			at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.runTests(RemoteTestRunner.java:763)
			at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.run(RemoteTestRunner.java:463)
			at org.eclipse.jdt.internal.junit.runner.RemoteTestRunner.main(RemoteTestRunner.java:209)
		Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'sendPublication': Unsatisfied dependency expressed through field 'messageService'; nested exception is org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'messageServiceImpl': Unsatisfied dependency expressed through field 'symClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'symphonyClient' defined in class path resource [com/anafi/symphony/bot/conf/BeansConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.symphonyoss.client.SymphonyClient]: Factory method 'symphonyClient' threw exception; nested exception is javax.ws.rs.ProcessingException: Error reading entity from input stream.
			at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
			at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
			at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
			at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
			at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
			at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
			at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197)
			at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761)
			at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867)
			at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543)
			at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693)
			at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360)
			at org.springframework.boot.SpringApplication.run(SpringApplication.java:303)
			at org.springframework.boot.test.context.SpringBootContextLoader.loadContext(SpringBootContextLoader.java:120)
			at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContextInternal(DefaultCacheAwareContextLoaderDelegate.java:98)
			at org.springframework.test.context.cache.DefaultCacheAwareContextLoaderDelegate.loadContext(DefaultCacheAwareContextLoaderDelegate.java:116)
			... 25 more
		Caused by: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'messageServiceImpl': Unsatisfied dependency expressed through field 'symClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'symphonyClient' defined in class path resource [com/anafi/symphony/bot/conf/BeansConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.symphonyoss.client.SymphonyClient]: Factory method 'symphonyClient' threw exception; nested exception is javax.ws.rs.ProcessingException: Error reading entity from input stream.
			at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588)
			at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
			at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
			at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
			at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
			at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
			at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
			at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
			at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
			at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
			at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
			... 43 more
		Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'symphonyClient' defined in class path resource [com/anafi/symphony/bot/conf/BeansConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.symphonyoss.client.SymphonyClient]: Factory method 'symphonyClient' threw exception; nested exception is javax.ws.rs.ProcessingException: Error reading entity from input stream.
			at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513)
			at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483)
			at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306)
			at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
			at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302)
			at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202)
			at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208)
			at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
			at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066)
			at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585)
			... 56 more
		Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [org.symphonyoss.client.SymphonyClient]: Factory method 'symphonyClient' threw exception; nested exception is javax.ws.rs.ProcessingException: Error reading entity from input stream.
			at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189)
			at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588)
			... 68 more
		Caused by: javax.ws.rs.ProcessingException: Error reading entity from input stream.
			at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:889)
			at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:834)
			at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:368)
			at org.glassfish.jersey.client.InboundJaxrsResponse$2.call(InboundJaxrsResponse.java:126)
			at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
			at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
			at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
			at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:419)
			at org.glassfish.jersey.client.InboundJaxrsResponse.runInScopeIfPossible(InboundJaxrsResponse.java:267)
			at org.glassfish.jersey.client.InboundJaxrsResponse.readEntity(InboundJaxrsResponse.java:123)
			at org.symphonyoss.symphony.pod.invoker.ApiClient.deserialize(ApiClient.java:564)
			at org.symphonyoss.symphony.pod.invoker.ApiClient.invokeAPI(ApiClient.java:697)
			at org.symphonyoss.symphony.pod.api.SessionApi.v2SessioninfoGet(SessionApi.java:123)
			at org.symphonyoss.symphony.clients.impl.UsersClientImpl.getUserBySession(UsersClientImpl.java:455)
			at org.symphonyoss.client.impl.SymphonyBasicClient.init(SymphonyBasicClient.java:308)
			at org.symphonyoss.client.impl.SymphonyBasicClient.init(SymphonyBasicClient.java:235)
			at com.anafi.symphony.bot.client.SymphonyClientImpl.init(SymphonyClientImpl.java:45)
			at com.anafi.symphony.bot.client.SymphonyClientImpl.init(SymphonyClientImpl.java:30)
			at com.anafi.symphony.bot.client.SymphonyClientFactory.getClient(SymphonyClientFactory.java:73)
			at com.anafi.symphony.bot.conf.BeansConfiguration.symphonyClient(BeansConfiguration.java:39)
			at com.anafi.symphony.bot.conf.BeansConfiguration$$EnhancerBySpringCGLIB$$67474e30.CGLIB$symphonyClient$1(<generated>)
			at com.anafi.symphony.bot.conf.BeansConfiguration$$EnhancerBySpringCGLIB$$67474e30$$FastClassBySpringCGLIB$$54bd75b.invoke(<generated>)
			at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
			at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
			at com.anafi.symphony.bot.conf.BeansConfiguration$$EnhancerBySpringCGLIB$$67474e30.symphonyClient(<generated>)
			at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
			at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
			at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
			at java.lang.reflect.Method.invoke(Method.java:498)
			at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
			... 69 more
		Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "roles" (class org.symphonyoss.symphony.pod.model.UserV2), not marked as ignorable (15 known properties: "lastName", "workPhoneNumber", "displayName", "department", "location", "username", "emailAddress", "avatars", "id", "company", "division", "mobilePhoneNumber", "title", "firstName", "jobFunction"])
		 at [Source: org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream@5fde1d64; line: 1, column: 349] (through reference chain: org.symphonyoss.symphony.pod.model.UserV2["roles"])
			at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:62)
			at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:834)
			at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1093)
			at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1489)
			at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1467)
			at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:282)
			at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140)
			at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:1583)
			at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:964)
			at com.fasterxml.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:815)
			at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:256)
			at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:235)
			at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:155)
			at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1085)
			at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:874)
			... 98 more

i use symphony-client 1.1.4
                 
                <dependency>
			<groupId>org.symphonyoss.symphony</groupId>
			<artifactId>symphony-client</artifactId>
			<version>1.1.4</version>
		</dependency>

In the UserV2 class, i not fouand any roles attribute !!
The class is in symphony-pod-java-jersey2-client-x.xx.x.jar

**Comment by ftbb** [comment]
Please see issue: https://github.com/symphonyoss/symphony-java-client/issues/109

roles and other attributes were most likely added to recent Symphony APIs

**Comment by darkmanAmazigh** [comment]
Thank you for your quick response,
excuse me but i can't link my issue with the #109 issue,
the problème is com from ClientConfig ?
  public class SymphonyExaneClientImpl extends SymphonyBasicClient implements SymphonyExaneClient {

    private ApiVersion apiVersion = ApiVersion.V4;

    public SymphonyExaneClientImpl(ApiVersion apiVersion) {
        this.apiVersion = apiVersion;
    }

    public SymphonyExaneClientImpl() {
        this(ApiVersion.V4);
    }


    public void init(Client httpClient, ConfigurationExaneApp initParams)
            throws InitException, AuthenticationException {
        setDefaultHttpClient(httpClient);

        init(getDefaultHttpClient(), getDefaultHttpClient(), initParams);

    }

    public void init(Client podHttpClient, Client agentHttpClient, ConfigurationExaneApp initParams)
            throws InitException, AuthenticationException {

        setPodHttpClient(podHttpClient);
        setAgentHttpClient(agentHttpClient);
        setDefaultHttpClient(podHttpClient);

        AuthenticationClient authClient = new AuthenticationClient(initParams.getSessionAuthUrl(), initParams.getKeyAuthUrl(), podHttpClient);

        SymAuth symAuth = authClient.authenticate();

        init(symAuth, initParams.getUserEmail(), initParams.getAgentUrl(), initParams.getPodUrl(), false);

    }

   }

**Comment by ftbb** [comment]
yes.. it does, you need to register the following to the ClientConfig before init of the Client.
     
     import org.symphonyoss.symphony.pod.invoker.JSON;

     clientConfig.register(new JSON());


How are you creating the httpClient? 

********

public void init(**Client httpClient**, ConfigurationExaneApp initParams)
        throws InitException, AuthenticationException {
   **setDefaultHttpClient(httpClient);**

*****

**Comment by darkmanAmazigh** [comment]
package com..anafi.symphony.bot.client;

import com..anafi.symphony.bot.conf.ConfigurationApp;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.symphonyoss.client.SymphonyClient;
import org.symphonyoss.client.SymphonyClientFactory;
import org.symphonyoss.client.exceptions.InitException;
import org.symphonyoss.client.exceptions.NetworkException;
import org.symphonyoss.client.impl.CustomHttpClient;
import org.symphonyoss.symphony.clients.model.ApiVersion;

import javax.ws.rs.client.Client;

public class SymphonyClientFactory extends SymphonyClientFactory {

    private static final Logger log = LoggerFactory.getLogger(SymphonyClientFactory.class);

    /**
     * Generate a new SymphonyClient based on type
     *
     * @param type The type of SymphonyClient.  Currently only BASIC is available.
     * @return A SymphonyClient instance based on type
     */
    public static SymphonyClient getClient(TYPE type) {

        return type.toString().equals(ApiVersion.V4.toString()) ? new SymphonyClientImpl(ApiVersion.V4) : new SymphonyClientImpl();

    }

    /**
     * Generate a new SymphonyClient and init it based on type
     *
     * @param type       The type of SymphonyClient.  Currently only BASIC is available.
     * @param initParams SymphonyClientConfig to init
     * @return A SymphonyClient instance based on type which is already instantiated.
     */
    public static SymphonyClient getClient(TYPE type, ConfigurationApp initParams) {


        try {

            //Create a basic client instance.
            SymphonyClient symClient = SymphonyClientFactory.getClient(type);

            log.debug("{} {}", initParams.getSessionAuthUrl(),
                    initParams.getKeyAuthUrl());


            try {
                Client httpClient;
                if (initParams.getTruststoreFile() != null) {
                    httpClient = CustomHttpClient.getClient(
                            initParams.getUserCertFile(),
                            initParams.getUserPassword(),
                            initParams.getTruststoreFile(),
                            initParams.getTruststorePassword());

                } else {
                    httpClient = CustomHttpClient.getClient(
                            initParams.getUserCertFile(),
                            initParams.getUserPassword());
                }


                symClient.setDefaultHttpClient(httpClient);
            } catch (Exception e) {
                log.error("Failed to create custom http client", e);
                return null;
            }


            symClient.init(symClient.getDefaultHttpClient(), initParams);


            return symClient;

        } catch (NetworkException ae) {

            log.error(ae.getMessage(), ae);
        } catch (InitException e) {
            log.error("error", e);
        }

        return null;
    }


}

**Comment by ftbb** [comment]
Change your getClient method.

        ClientConfig clientConfig = new ClientConfig();
        clientConfig.register(new JSON());
        clientConfig.register(JacksonFeature.class);

        //If  try {
            Client httpClient;
            if (initParams.getTruststoreFile() != null) {
                httpClient = CustomHttpClient.getClient(
                        initParams.getUserCertFile(),
                        initParams.getUserPassword(),
                        initParams.getTruststoreFile(),
                        initParams.getTruststorePassword(),
                        clientConfig);

            } else {
                httpClient = CustomHttpClient.getClient(
                        initParams.getUserCertFile(),
                        initParams.getUserPassword(),
                        clientConfig);
            }

**Comment by darkmanAmazigh** [comment]
So i must change All my Client to Client Config ?

When i add symClient.getDefaultHttpClient().register(new JSON()); that work with Client, but i got zero message,

**Comment by ftbb** [comment]
you wouldn't get a message from registration.

you can add the ClientConfig or register direct, but should do it before init of the SymClient.

**Comment by darkmanAmazigh** [comment]
i got nullpointerexception with symCliient.getMessageService()... in this class

   package com.exane.anafi.symphony.bot.conf;

import com.exane.anafi.symphony.bot.client.SymphonyExaneClientFactory;
import com.exane.anafi.symphony.bot.commun.Encryptor;
import com.exane.anafi.symphony.bot.commun.MLMessageBuilder;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.web.client.RestTemplate;
import org.symphonyoss.client.SymphonyClient;
import org.symphonyoss.client.SymphonyClientFactory;
import org.symphonyoss.client.exceptions.MessagesException;
import org.symphonyoss.client.services.MessageListener;
import org.symphonyoss.symphony.clients.model.SymMessage;

@Configuration
public class BeansConfiguration {

    private Logger log = LoggerFactory.getLogger(BeansConfiguration.class);

    @Autowired
    private ConfigurationExaneApp configurationExaneApp;

    @Autowired
    private MLMessageBuilder mlMessageBuilder;

    @Bean
    public RestTemplate restTemplate() {

        return new RestTemplate();

    }

    @Bean
    public SymphonyClient symphonyClient() {

        SymphonyClient symCilent = SymphonyExaneClientFactory.getClient(SymphonyClientFactory.TYPE.BASIC, configurationExaneApp);

        symCilent.getMessageService().addMessageListener(new MessageListener() {

            @Override
            public void onMessage(SymMessage symMessage) {

                if (symMessage.getFromUserId() != symCilent.getLocalUser().getId()) {

                    SymMessage message = new SymMessage();

                    message.setMessage(mlMessageBuilder.bold("Please do not reply! for more information ").link("mailto:cube@exanebnpparibas.com", "Contact Us").build());

                    try {

                        symCilent.getMessageService().sendMessage(symMessage.getSymUser(), message);

                    } catch (MessagesException e) {

                        log.error(e.getMessage());

                    }

                }

            }

        });

        return symCilent;

    }

    @Bean
    public Encryptor encryptor() {

        return new Encryptor();

    }

   }

**Comment by ftbb** [comment]
Change to V4

SymphonyClient symCilent = SymphonyExaneClientFactory.getClient(SymphonyClientFactory.TYPE.V4, configurationExaneApp);

**Comment by darkmanAmazigh** [comment]
The same error, 
  
        Caused by: java.lang.NullPointerException
	at com.exane.anafi.symphony.bot.conf.BeansConfiguration.symphonyClient(BeansConfiguration.java:41)
	at com.exane.anafi.symphony.bot.conf.BeansConfiguration$$EnhancerBySpringCGLIB$$3006d862.CGLIB$symphonyClient$1(<generated>)
	at com.exane.anafi.symphony.bot.conf.BeansConfiguration$$EnhancerBySpringCGLIB$$3006d862$$FastClassBySpringCGLIB$$5490613c.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invokeSuper(MethodProxy.java:228)
	at org.springframework.context.annotation.ConfigurationClassEnhancer$BeanMethodInterceptor.intercept(ConfigurationClassEnhancer.java:358)
	at com.exane.anafi.symphony.bot.conf.BeansConfiguration$$EnhancerBySpringCGLIB$$3006d862.symphonyClient(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:162)
	... 69 more

**Comment by ftbb** [comment]
I have no idea as this is your side of the code.  

You would need to debug why the SymphonyClient symCilent is null after init.  

You should see logging on SymphonyClient init

**Comment by darkmanAmazigh** [comment]
Thanks a lot for your time @ftbb , i'll debug, and let you knew if i found the origin of problem

**Comment by darkmanAmazigh** [comment]
Thank you a lot @ftbb , adding just this line at my code resolve my problem : 
     
                          symClient.getDefaultHttpClient().register(new JSON());
