### ISSUE TITLE
Exception in RoomService when message is sent

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/symphony-java-client#18]
**Steps to reproduce:**
* Create a bot that has a RoomServiceListener (doesn't matter what it does), and register it using RoomService
* Run the bot
* Start a 1:1 chat with the bot's user, and send it the message "Hi" from the Symphony UI

**Expected result:**
The bot's `RoomServiceListener.onMessage` method is called.

**Actual result:**
The following exception is thrown:
```
2016-09-24 17:56:46 DEBUG MessageFeedWorker:87 - Received 1 messages..
2016-09-24 17:56:46 DEBUG MessageService:126 - MessageID: QXkJnzgVsPxWJ4E135Sk9n___qihJ9n-dA StreamID: 8wd_4nJcHAY3t2QyUEz3kH___qihesp1dA
2016-09-24 17:56:46 DEBUG MessageService:202 - Found new room stream to cache: 8wd_4nJcHAY3t2QyUEz3kH___qihesp1dA
2016-09-24 17:56:46 ERROR RoomService:129 - Unable to add new room from message:
org.symphonyoss.exceptions.RoomException: Room is not fully defined.  Check ID and stream ID
	at org.symphonyoss.client.services.RoomService.joinRoom(RoomService.java:97)
	at org.symphonyoss.client.services.RoomService.addRoom(RoomService.java:142)
	at org.symphonyoss.client.services.RoomService.onMessage(RoomService.java:117)
	at org.symphonyoss.client.services.MessageService.onMessage(MessageService.java:143)
	at java.util.ArrayList.forEach(ArrayList.java:1249)
	at org.symphonyoss.client.services.MessageFeedWorker.run(MessageFeedWorker.java:90)
	at java.lang.Thread.run(Thread.java:745)
2016-09-24 17:56:46 DEBUG MessageService:156 - TS: 1474765006350
From ID: 346621040656389
```

**Comment by ftbb** [comment]
Commit: f08d59b19856300212df8396ea859d451abfec8e

Really stupid issue with not setting roomID from stream setter. 

Tested and deployed snapshot.
