### ISSUE TITLE
Exception handling loses all original error messages from symphony APIs. The replacement messages are not meaningful and don't tell the right cause.

### ISSUE THREAD

**Issue by shirleyshan** [symphonyoss/symphony-java-client#25]
For example, when calling the method StreamsClient.createChatRoom(SymRoomAttributes), symphony RESTful API returns "The name 'shirley' is too similar to one that is already in use. Please choose another name". But this method eats the original error and returns me "Failed to obtain room information while creating room:", which isn't helpful at all.

**Comment by ftbb** [comment]
Just tested...we also provide the underlying stacktrace..

In the stacktrace below, you will see that I've tried to create room "Symbols" that already exists..

The underlying REST API call is returning "{"code":400,"message":"The name 'Symbols' is too similar to one that is already in use. Please choose another name."}"

We can propagate the the underlying message to the L1 if you like, which might make more sense.   Leaving this open as enhancement.

--------------
org.symphonyoss.exceptions.StreamsException: Failed to obtain room information while creating room: Symbols
	at org.symphonyoss.symphony.clients.impl.StreamsClientImpl.createChatRoom(StreamsClientImpl.java:171)
	at org.symphonyoss.examples.roomsession.RoomServiceExample.init(RoomServiceExample.java:162)
	at org.symphonyoss.examples.roomsession.RoomServiceExample.<init>(RoomServiceExample.java:83)
	at org.symphonyoss.examples.roomsession.RoomServiceExample.main(RoomServiceExample.java:90)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.symphonyoss.symphony.pod.invoker.ApiException: {"code":400,"message":"The name 'Symbols' is too similar to one that is already in use. Please choose another name."}
	at org.symphonyoss.symphony.pod.invoker.ApiClient.invokeAPI(ApiClient.java:659)
	at org.symphonyoss.symphony.pod.api.StreamsApi.v2RoomCreatePost(StreamsApi.java:403)
	at org.symphonyoss.symphony.clients.impl.StreamsClientImpl.createChatRoom(StreamsClientImpl.java:167)
	... 8 more

**Comment by pmonks** [comment]
Just validated that this appears to be fixed.  Ok to close from me!
