### ISSUE TITLE
How to make sure datafeed starts?

### ISSUE THREAD

**Issue by evereveron** [symphonyoss/symphony-java-client#47]
I am running ChatExample.java and am getting a "DataFeedException: Could not start datafeed.. "

- SessionToken created
- KeyToken was created. 
- It is able to find my user
- able to find the bot,
- able to find Stream
- able to detect the chat session.
- fails to send message

The full error stack is as follows:

2017-03-03 15:49:34 INFO  MessageFeedWorker:91 - Creating datafeed with pod...
2017-03-03 15:49:34 ERROR MessageFeedWorker:98 - Failed to create datafeed with pod, please check connection..
org.symphonyoss.exceptions.DataFeedException: Could not start datafeed..
	at org.symphonyoss.symphony.clients.impl.DataFeedClientImpl.createDatafeed(DataFeedClientImpl.java:91)
	at org.symphonyoss.client.services.MessageFeedWorker.initDatafeed(MessageFeedWorker.java:93)
	at org.symphonyoss.client.services.MessageFeedWorker.run(MessageFeedWorker.java:72)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.symphonyoss.symphony.agent.invoker.ApiException: {"code":500,"message":"Failed to create a session: Failed to init:\n"}
	at org.symphonyoss.symphony.agent.invoker.ApiClient.invokeAPI(ApiClient.java:659)
	at org.symphonyoss.symphony.agent.api.DatafeedApi.v1DatafeedCreatePost(DatafeedApi.java:89)
	at org.symphonyoss.symphony.clients.impl.DataFeedClientImpl.createDatafeed(DataFeedClientImpl.java:89)
	... 3 more

2017-03-03 15:49:35 DEBUG ChatExample:243 - New chat session detected on stream bz70d6dp0_PDqPJDfe03e3___qWN4fNrdA with [344147139494497:Jasmine Feng] 
2017-03-03 15:49:35 ERROR ChatExample:206 - error
org.symphonyoss.exceptions.MessagesException: Failed to send message to stream: bz70d6dp0_PDqPJDfe03e3___qWN4fNrdA
	at org.symphonyoss.symphony.clients.impl.MessagesClientImpl.sendMessage(MessagesClientImpl.java:138)
	at org.symphonyoss.client.services.MessageService.sendMessage(MessageService.java:113)
	at testingstuff.ChatExample.init(ChatExample.java:192)
	at testingstuff.ChatExample.<init>(ChatExample.java:84)
	at testingstuff.ChatExample.main(ChatExample.java:91)
Caused by: org.symphonyoss.symphony.agent.invoker.ApiException: {"code":500,"message":"Failed to create a session: Failed to init:\n"}
	at org.symphonyoss.symphony.agent.invoker.ApiClient.invokeAPI(ApiClient.java:659)
	at org.symphonyoss.symphony.agent.api.MessagesApi.v2StreamSidMessageCreatePost(MessagesApi.java:297)
	at org.symphonyoss.symphony.clients.impl.MessagesClientImpl.sendMessage(MessagesClientImpl.java:136)
	... 4 more

**Comment by ftbb** [comment]
Hello..  This smells like you are having a problem with the Agent Server.

All other calls are going to Sessionauth, Keymanager and Pod.

Anything related to sending messages (encrypting data) goes through Agent server local to your network.   This includes both Datafeed and message calls.

Can you please check your logs on the agent server?  The agent server will proxy all communications to your Pod for message transmission.  The logs on that agent server should provide details as to why the session is failing.  

Also sent a request of Symphony to chat offline if you like.

**Comment by ftbb** [comment]
This was related to setup.
