### ISSUE TITLE
Exceptions should include the endpoint they called

### ISSUE THREAD

**Issue by pmonks** [symphonyoss/symphony-java-client#52]
When an exception occurs as the result of a call to the server, it would greatly facilitate troubleshooting (especially when chatting with Symphony support) to know precisely which endpoint failed. 

Here's an example of an exception I'm getting, but it's hard to be sure which endpoint it is that's causing the `403`:

```
org.symphonyoss.exceptions.StreamsException: Failed to retrieve stream for given user ids...
	at org.symphonyoss.symphony.clients.impl.StreamsClientImpl.getStreams(StreamsClientImpl.java:203)
	at clj_symphony.stream$get_streamobjs.invokeStatic(stream.clj:54)
	at clj_symphony.stream$get_streamobjs.invoke(stream.clj:51)
	at clj_symphony.stream$get_streams.invokeStatic(stream.clj:62)
	at clj_symphony.stream$get_streams.invoke(stream.clj:59)
	at user$eval2045.invokeStatic(form-init3019237959863748315.clj:1)
	at user$eval2045.invoke(form-init3019237959863748315.clj:1)
	at clojure.lang.Compiler.eval(Compiler.java:6927)
	at clojure.lang.Compiler.eval(Compiler.java:6890)
	at clojure.core$eval.invokeStatic(core.clj:3105)
	at clojure.core$eval.invoke(core.clj:3101)
	at clojure.main$repl$read_eval_print__7408$fn__7411.invoke(main.clj:240)
	at clojure.main$repl$read_eval_print__7408.invoke(main.clj:240)
	at clojure.main$repl$fn__7417.invoke(main.clj:258)
	at clojure.main$repl.invokeStatic(main.clj:258)
	at clojure.main$repl.doInvoke(main.clj:174)
	at clojure.lang.RestFn.invoke(RestFn.java:1523)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate$fn__648.invoke(interruptible_eval.clj:87)
	at clojure.lang.AFn.applyToHelper(AFn.java:152)
	at clojure.lang.AFn.applyTo(AFn.java:144)
	at clojure.core$apply.invokeStatic(core.clj:646)
	at clojure.core$with_bindings_STAR_.invokeStatic(core.clj:1881)
	at clojure.core$with_bindings_STAR_.doInvoke(core.clj:1881)
	at clojure.lang.RestFn.invoke(RestFn.java:425)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invokeStatic(interruptible_eval.clj:85)
	at clojure.tools.nrepl.middleware.interruptible_eval$evaluate.invoke(interruptible_eval.clj:55)
	at clojure.tools.nrepl.middleware.interruptible_eval$interruptible_eval$fn__693$fn__696.invoke(interruptible_eval.clj:222)
	at clojure.tools.nrepl.middleware.interruptible_eval$run_next$fn__688.invoke(interruptible_eval.clj:190)
	at clojure.lang.AFn.run(AFn.java:22)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.symphonyoss.symphony.pod.invoker.ApiException: {"code":403,"message":"user does not have the proper privilege to perform this action."}
	at org.symphonyoss.symphony.pod.invoker.ApiClient.invokeAPI(ApiClient.java:659)
	at org.symphonyoss.symphony.pod.api.StreamsApi.v1AdminStreamsListPost(StreamsApi.java:201)
	at org.symphonyoss.symphony.clients.impl.StreamsClientImpl.getStreams(StreamsClientImpl.java:197)
	... 31 more
```

(fwiw I'm 99% sure it's either `/v1/streams/list` or `/v1/admin/streams/list`, but can't tell from the exception)

**Comment by ftbb** [comment]
I don't know if we improved this all too much other than providing better details on the underlying exception from the downstream language binding.  See new exceptions handling in 1.0.2 SNAPSHOT.  Interested in your views.

**Comment by ftbb** [comment]
Any update @pmonks ?  Did you have a chance to test?
