### ISSUE TITLE
Restarted Pod Loses DataFeed?

### ISSUE THREAD

**Issue by robmoffat** [symphonyoss/symphony-java-client#68]
Hi,

I think I had a case where over the weekend recently Symphony upgraded our test pod.  As a result of this, the bot I had written wasn't receiving messages.

It uses 

```java
symClient.getMessageService().addChatListener(msg -> onChatMessage(msg));
```

Is it possible that the API doesn't have any reconnect logic in it for this occurrence?  If so, should I write some, or would this be better handled within the client API?

cheers,

Rob

**Comment by ftbb** [comment]
The SJC has recovery logic built into the MessageService, which underpins the real-time feed of data for all services. 

Can you provide output logs/stacktrace during the upgrade which would indicate a disruption and recovery?  I can take a look to see if there is an issue or not.

**Comment by robmoffat** [comment]
Ok, I *think* this is it (from Sunday):

```
2017-09-10 11:51:49,459 ERROR [Thread-5][] o.s.c.s.MessageFeedWorker - Failed to create read datafeed from pod, please check connection..resetting.
org.symphonyoss.client.exceptions.DataFeedException: Failed to retrieve messages from datafeed... to https://hkg3vl3163o.hk.hsbc:8444/agent
endpoint https://hkg3vl3163o.hk.hsbc:8444/agent
httpStatus 400
        at org.symphonyoss.symphony.clients.impl.DataFeedClientImpl.getEventsFromDatafeed(DataFeedClientImpl.java:181)
        at org.symphonyoss.symphony.clients.impl.DataFeedClientImpl.getEventsFromDatafeed(DataFeedClientImpl.java:191)
        at org.symphonyoss.client.services.MessageFeedWorker.readDatafeed(MessageFeedWorker.java:143)
        at org.symphonyoss.client.services.MessageFeedWorker.run(MessageFeedWorker.java:79)
        at java.lang.Thread.run(Thread.java:745)
Caused by: org.symphonyoss.symphony.agent.invoker.ApiException: {"code":400,"message":"Could not find a datafeed with the id: 19dbb33b-910c-402e-ba9c-01ea1f6a5f37"}
        at org.symphonyoss.symphony.agent.invoker.ApiClient.invokeAPI(ApiClient.java:708)
        at org.symphonyoss.symphony.agent.api.DatafeedApi.v4DatafeedIdReadGet(DatafeedApi.java:321)
        at org.symphonyoss.symphony.clients.impl.DataFeedClientImpl.getEventsFromDatafeed(DataFeedClientImpl.java:176)
        ... 4 common frames omitted
2017-09-10 11:51:49,460 INFO  [Thread-5][] o.s.c.s.MessageFeedWorker - Creating datafeed with pod...
```

So, in this case, it seemed to retry and connect again, but then:

```java
2017-09-10 13:05:04,916 ERROR [Thread-5][] o.s.c.s.MessageFeedWorker - Failed to create read datafeed from pod, please check connection..resetting.
javax.ws.rs.ProcessingException: java.net.ConnectException: Connection refused
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:287)
        at org.glassfish.jersey.client.ClientRuntime.invoke(ClientRuntime.java:252)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:684)
        at org.glassfish.jersey.client.JerseyInvocation$1.call(JerseyInvocation.java:681)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
        at org.glassfish.jersey.internal.Errors.process(Errors.java:228)
        at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:444)
        at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:681)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:411)
        at org.glassfish.jersey.client.JerseyInvocation$Builder.get(JerseyInvocation.java:311)
        at org.symphonyoss.symphony.agent.invoker.ApiClient.invokeAPI(ApiClient.java:671)
        at org.symphonyoss.symphony.agent.api.DatafeedApi.v4DatafeedIdReadGet(DatafeedApi.java:321)
        at org.symphonyoss.symphony.clients.impl.DataFeedClientImpl.getEventsFromDatafeed(DataFeedClientImpl.java:176)
        at org.symphonyoss.symphony.clients.impl.DataFeedClientImpl.getEventsFromDatafeed(DataFeedClientImpl.java:191)
        at org.symphonyoss.client.services.MessageFeedWorker.readDatafeed(MessageFeedWorker.java:143)
        at org.symphonyoss.client.services.MessageFeedWorker.run(MessageFeedWorker.java:79)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.net.ConnectException: Connection refused
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.http.HttpClient.parseHTTPHeader(HttpClient.java:781)
        at sun.net.www.http.HttpClient.parseHTTP(HttpClient.java:647)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1536)
        at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1441)
        at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:338)
        at org.glassfish.jersey.client.internal.HttpUrlConnector._apply(HttpUrlConnector.java:394)
        at org.glassfish.jersey.client.internal.HttpUrlConnector.apply(HttpUrlConnector.java:285)
        ... 17 common frames omitted
2017-09-10 13:05:04,916 INFO  [Thread-5][] o.s.c.s.MessageFeedWorker - Creating datafeed with pod...
```

But then on Monday morning, it wasn't responding.  So, not much of help in the logs I guess.

**Comment by ftbb** [comment]
Think this is fixed now.  Wasn't catching RuntimeException's as a result of certain network errors.

It's in the develop branch (1.1.0-SNAPSHOT build).

commit f47fcaad2f2cde749bd3d331695a753a0fa2e33b

**Comment by robmoffat** [comment]
cheers, Frank.  Will check it out.

**Comment by robmoffat** [comment]
This seems fixed in the new version, cheers!
