### ISSUE TITLE
Include URL in ApiExceptions

### ISSUE THREAD

**Issue by paul-symphony** [symphonyoss/symphony-java-client#7]
First time setup and run landed on the below error, which provides little to no insight into what is wrong.  Now one has to dig through dependency source code and/or debug to figure out what URL is wrong and why.
```
INFO  14:15:31 MessageFeedWorker: Creating datafeed with pod...
org.symphonyoss.symphony.pod.invoker.ApiException: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.6.3</center>
</body>
</html>

	at org.symphonyoss.symphony.pod.invoker.ApiClient.invokeAPI(ApiClient.java:643)
	at org.symphonyoss.symphony.pod.api.PresenceApi.v1PresenceGet(PresenceApi.java:85)
	at org.symphonyoss.symphony.clients.impl.PresenceClientImpl.getAllUserPresence(PresenceClientImpl.java:65)
	at org.symphonyoss.client.services.PresenceService.getAllUserPresence(PresenceService.java:65)
	at org.symphonyoss.client.services.PresenceService.<init>(PresenceService.java:54)
	at org.symphonyoss.client.impl.SymphonyBasicClient.init(SymphonyBasicClient.java:87)
	at org.ppollack.symphony.faqbot.ChatExample.init(ChatExample.java:69)
	at org.ppollack.symphony.faqbot.ChatExample.<init>(ChatExample.java:26)
	at org.ppollack.symphony.faqbot.ChatExample.main(ChatExample.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
org.symphonyoss.symphony.pod.invoker.ApiException: <html>
<head><title>404 Not Found</title></head>
<body bgcolor="white">
<center><h1>404 Not Found</h1></center>
<hr><center>nginx/1.6.3</center>
</body>
</html>

	at org.symphonyoss.symphony.pod.invoker.ApiClient.invokeAPI(ApiClient.java:643)
	at org.symphonyoss.symphony.pod.api.UsersApi.v1UserGet(UsersApi.java:95)
	at org.symphonyoss.symphony.clients.impl.UsersClientImpl.getUserFromEmail(UsersClientImpl.java:66)
	at org.symphonyoss.client.impl.SymphonyBasicClient.init(SymphonyBasicClient.java:90)
	at org.ppollack.symphony.faqbot.ChatExample.init(ChatExample.java:69)
	at org.ppollack.symphony.faqbot.ChatExample.<init>(ChatExample.java:26)
	at org.ppollack.symphony.faqbot.ChatExample.main(ChatExample.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:134)
```

**Comment by ftbb** [comment]
Agreed, 

Exceptions management is extremely poor right now.

Improvements underway.

**Comment by ftbb** [comment]
Commit 161596105b93035ea7902ae7cf90f072e249d87e
Implemented full exception management pack for all Symphony clients.

Exception reports are more detailed.
